### ISSUE TITLE
Travis CI Caching

### ISSUE THREAD

**Issue by tonyhhyip** [guardian-ils/Guardian#26]
Travis CI need to download all the composer package every time, composer provide cache in $HOME/.composer, so I think adding this as a cache is a good idea

**Comment by yookoala** [comment]
Mmm... Not entirely. It is slow like hell, but it tells you when something breaks in new installations (may due to upstream issues).

**Comment by linquize** [comment]
Can travis CI do caching?

**Comment by tonyhhyip** [comment]
@linquize Yes, it can.
https://docs.travis-ci.com/user/caching/

**Comment by tonyhhyip** [comment]
Handled by PR #30
